This file is for basic cleaning tasks on the main dataset, including dropping redundant columns and renaming things for clarity.

In [10]:
import pandas as pd

In [15]:
df = pd.read_csv("../3.3 Construct Data/merged_data_combined_budgets_and_revs.csv")

#drops useless index columns
df = df.drop('Unnamed: 0.5', axis=1)
df = df.drop('Unnamed: 0.4', axis=1)
df = df.drop('Unnamed: 0.3', axis=1)
df = df.drop('Unnamed: 0.2', axis=1)
df = df.drop('Unnamed: 0.1', axis=1)
df = df.drop('Unnamed: 0', axis=1)


#drop redundant columns
df = df.drop('ID', axis = 1)
df = df.drop('imdb_ids', axis = 1)

#renames columns to add legibility
df.rename(columns={'movie_id': 'TMDB ID', 'Title_y': 'TMDB Title', 'Title_x': 'IMDB Title', 'Budget_y': 'TMDB Budget (With Floor)', 'Budget_x': 'IMDB Budget', 'Revenue_y': 'TMDB Revenue'},inplace = True)
print(df.head)
df.to_csv("clean_merged_data.csv",index=False)

<bound method NDFrame.head of      Running Time                               Genres  \
0     1 hr 22 min                    Documentary Sport
1           8 min                        History Short
2     1 hr 49 min  Action Crime Drama Mystery Thriller
3     1 hr 30 min                                Drama
4     1 hr 46 min          Biography Drama History War
...           ...                                  ...
6460          NaN                              Mystery
6461  1 hr 35 min                                Drama
6462  1 hr 29 min                          Documentary
6463  1 hr 32 min                          Documentary
6464  1 hr 34 min                             Thriller

                         IMDB Title   MPAA   Domestic Distributor  \
0              Into the Mind (2013)    NaN                    NaN
1     In Search of Lost Time (2013)    NaN                    NaN
2                Broken City (2013)      R  Twentieth Century Fox
3            Redwood Highway (2013)  PG-13         Monterey Media
4           Bless Me, Ultima (2012)  PG-13   Arenas Entertainment
...                             ...    ...                    ...
6460    Batman: Stained Heir (2022)    NaN                    NaN
6461     Edward and Isabella (2022)    NaN                    NaN
6462              2000 Mules (2022)    NaN          D'Souza Media
6463              Fire Front (2022)    NaN                    NaN
6464                Stowaway (2021)      R                    NaN

      Domestic Opening              Earliest Release Date  IMDB Budget  \
0                  NaN           January 31, 2014 (Spain)          0.0
1                  NaN   September 30, 2007 (South Korea)          0.0
2            8268908.0  January 18, 2013 (Domestic, EMEA)   35000000.0
3                 30.0          April 11, 2014 (Domestic)          0.0
4             470109.0       February 22, 2013 (Domestic)          0.0
...                ...                                ...          ...
6460               NaN                                NaN          0.0
6461               NaN                                NaN          0.0
6462          751755.0            May 20, 2022 (Domestic)          0.0
6463               NaN                                NaN          0.0
6464               NaN           August 4, 2022 (Croatia)          0.0

      TMDB Budget (With Floor)        Genre ID  ...  \
0                          0.0            [99]  ...
1                          0.0            [99]  ...
2                   56000000.0    [53, 80, 18]  ...
3                          0.0            [18]  ...
4                          0.0     [18, 10752]  ...
...                        ...             ...  ...
6460                     600.0  [9648, 80, 28]  ...
6461                       0.0            [18]  ...
6462                       0.0            [99]  ...
6463                       0.0            [99]  ...
6464                       0.0            [53]  ...

                                               cast_ids  \
0     [124065, 587712, 587879, 582159, 90226, 582154...
1                                                    []
2     [13240, 934, 1922, 2954, 12834, 203096, 76511,...
3     [28778, 4139, 123516, 1169115, 62760, 7134, 11...
4     [1116235, 1163, 2137, 224507, 3979, 76857, 116...
...                                                 ...
6460  [4204989, 4204988, 4204990, 4204991, 4204992, ...
6461                                 [3620801, 1445943]
6462  [219861, 3528225, 89450, 1428427, 2161106, 551...
6463                                                 []
6464  [1246972, 1053422, 81685, 2447500, 2729541, 37...

                                                  order  \
0                           [0, 1, 2, 3, 4, 5, 6, 7, 8]
1                                                    []
2     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
3                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
4            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
...                                                 ...
6460     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
6461                                             [0, 1]
6462  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
6463                                                 []
6464  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...

                    director_ids domestic_revenue international_revenue  \
0               [112813, 590724]           2241.0                2241.0
1                      [3384263]             37.0                  37.0
2                        [11448]       19701164.0            15036035.0
3                       [133426]         134049.0              134049.0
4                        [21712]        1561962.0             1561962.0
...                          ...              ...                   ...
6460                   [4205005]              0.0                   NaN
6461                   [3620802]           4288.0                4288.0
6462  [219861, 1744296, 2756880]        1465513.0             1465513.0
6463                   [1374174]             64.0                  64.0
6464                   [1462081]          30556.0               30556.0

      worldwide_revenue  Release Year  \
0                   NaN          2013
1                   NaN          2013
2            34737199.0          2013
3                   NaN          2013
4                   NaN          2013
...                 ...           ...
6460                NaN          2022
6461                NaN          2022
6462                NaN          2022
6463                NaN          2022
6464                NaN          2022

                                            star_scores  Merged Budget  \
0         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]       100000.0
1                                                    []       100000.0
2     [309.5610869566243, 79.06365252626196, 57.2302...     35000000.0
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       100000.0
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       100000.0
...                                                 ...            ...
6460  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       100000.0
6461                                         [0.0, 0.0]       100000.0
6462  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       100000.0
6463                                                 []       100000.0
6464  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       100000.0

     Merged Revenue
0            2241.0
1              37.0
2        19701164.0
3          134049.0
4         1561962.0
...             ...
6460     69000000.0
6461         4288.0
6462      1465513.0
6463           64.0
6464        30556.0

[6465 rows x 29 columns]>

In [ ]:
: