In [2]:
import pandas as pd

In [16]:
df = pd.read_csv("merged_data_star_score_missing_added.csv")
df["Budget_x"].fillna(0,inplace=True)
df['Merged Budget'] = df.apply(lambda row: row['Budget_x'] if row['Budget_x'] != 0 else row['Budget_y'], axis=1)
df['Merged Budget'] = df['Merged Budget'].apply(lambda x: 100000 if x < 100000 else x)

print(df['Merged Budget'].head)

df["domestic_revenue"].fillna(0,inplace=True)
df['Merged Revenue'] = df.apply(lambda row: row['domestic_revenue'] if row['domestic_revenue'] != 0 else row['Revenue_y'], axis=1)
print(df["Merged Revenue"])

df = df[(df['Merged Budget'] != 0) & (df["Merged Revenue"] != 0)]
print(df.head)

df.to_csv("merged_data_combined_budgets_and_revs.csv", index = False)

<bound method NDFrame.head of 0        100000.0
1        199000.0
2        100000.0
3        100000.0
4        100000.0
           ...
35234    100000.0
35235    100000.0
35236    100000.0
35237    100000.0
35238    100000.0
Name: Merged Budget, Length: 35239, dtype: float64>
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
          ...
35234        0.0
35235       64.0
35236        0.0
35237        0.0
35238    30556.0
Name: Merged Revenue, Length: 35239, dtype: float64
<bound method NDFrame.head of        Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  \
6                 6           6.0             6             6         41418
7                 7           7.0             7             7         41419
8                 8           8.0             8             8         41420
29               29          29.0            29            29         41441
51               51          51.0            51            51         41463
...             ...           ...           ...           ...           ...
35196           122           NaN           122           122           122
35213           139           NaN           139           139           139
35228           154           NaN           154           154           154
35235           161           NaN           161           161           161
35238           164           NaN           164           164           164

       Unnamed: 0 Running Time                               Genres  \
6           41418  1 hr 22 min                    Documentary Sport
7           41419        8 min                        History Short
8           41420  1 hr 49 min  Action Crime Drama Mystery Thriller
29          41441  1 hr 30 min                                Drama
51          41463  1 hr 46 min          Biography Drama History War
...           ...          ...                                  ...
35196         123          NaN                              Mystery
35213         140  1 hr 35 min                                Drama
35228         155  1 hr 29 min                          Documentary
35235         162  1 hr 32 min                          Documentary
35238         165  1 hr 34 min                             Thriller

                             Title_x   MPAA  ...  \
6               Into the Mind (2013)    NaN  ...
7      In Search of Lost Time (2013)    NaN  ...
8                 Broken City (2013)      R  ...
29            Redwood Highway (2013)  PG-13  ...
51           Bless Me, Ultima (2012)  PG-13  ...
...                              ...    ...  ...
35196    Batman: Stained Heir (2022)    NaN  ...
35213     Edward and Isabella (2022)    NaN  ...
35228              2000 Mules (2022)    NaN  ...
35235              Fire Front (2022)    NaN  ...
35238                Stowaway (2021)      R  ...

                                                cast_ids  \
6      [124065, 587712, 587879, 582159, 90226, 582154...
7                                                     []
8      [13240, 934, 1922, 2954, 12834, 203096, 76511,...
29     [28778, 4139, 123516, 1169115, 62760, 7134, 11...
51     [1116235, 1163, 2137, 224507, 3979, 76857, 116...
...                                                  ...
35196  [4204989, 4204988, 4204990, 4204991, 4204992, ...
35213                                 [3620801, 1445943]
35228  [219861, 3528225, 89450, 1428427, 2161106, 551...
35235                                                 []
35238  [1246972, 1053422, 81685, 2447500, 2729541, 37...

                                                   order  \
6                            [0, 1, 2, 3, 4, 5, 6, 7, 8]
7                                                     []
8      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
29                    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
51            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
...                                                  ...
35196     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
35213                                             [0, 1]
35228  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
35235                                                 []
35238  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...

                     director_ids  domestic_revenue international_revenue  \
6                [112813, 590724]            2241.0                2241.0
7                       [3384263]              37.0                  37.0
8                         [11448]        19701164.0            15036035.0
29                       [133426]          134049.0              134049.0
51                        [21712]         1561962.0             1561962.0
...                           ...               ...                   ...
35196                   [4205005]               0.0                   NaN
35213                   [3620802]            4288.0                4288.0
35228  [219861, 1744296, 2756880]         1465513.0             1465513.0
35235                   [1374174]              64.0                  64.0
35238                   [1462081]           30556.0               30556.0

       worldwide_revenue  Release Year  \
6                    NaN          2013
7                    NaN          2013
8             34737199.0          2013
29                   NaN          2013
51                   NaN          2013
...                  ...           ...
35196                NaN          2022
35213                NaN          2022
35228                NaN          2022
35235                NaN          2022
35238                NaN          2022

                                             star_scores Merged Budget  \
6          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]      100000.0
7                                                     []      100000.0
8      [309.5610869566243, 79.06365252626196, 57.2302...    35000000.0
29     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      100000.0
51     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      100000.0
...                                                  ...           ...
35196  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      100000.0
35213                                         [0.0, 0.0]      100000.0
35228  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      100000.0
35235                                                 []      100000.0
35238  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      100000.0

      Merged Revenue
6             2241.0
7               37.0
8         19701164.0
29          134049.0
51         1561962.0
...              ...
35196     69000000.0
35213         4288.0
35228      1465513.0
35235           64.0
35238        30556.0

[6465 rows x 37 columns]>

'\nbudgets["Budget"] = df\n\nboth_nonzero_budgets = budgets[(budgets["Budget_y"] > 0) & (budgets["Budget_x"] > 0)]\nboth_nonzero_budgets["Difference"] = both_nonzero_budgets["Budget_x"] - both_nonzero_budgets["Budget_y"]\nprint(both_nonzero_budgets.head)\nprint(pd.Series.mean(both_nonzero_budgets["Difference"]))\n\ndf["domestic_revenue"].fillna(0,inplace=True)\nrevenues = df[["Revenue_y", "domestic_revenue"]]\nboth_nonzero_revenues = revenues[(revenues["Revenue_y"] > 0) & (revenues["domestic_revenue"] > 0)]\nboth_nonzero_revenues["Difference"] = both_nonzero_revenues["domestic_revenue"] - both_nonzero_revenues["Revenue_y"]\nprint(both_nonzero_revenues.head)\nprint(pd.Series.mean(both_nonzero_revenues["Difference"]))\n'